### ISSUE TITLE
Dropbox app frozen pending review

### ISSUE THREAD

**Issue by sabrehagen** [lemourin/libcloudstorage#11]
When trying to link dropbox using the following url, the below error is produced. Is this exact clientId required? Could it be substituted with another clientId that is owned by the user?

```
https://www.dropbox.com/oauth2/authorize?client_id=ktryxp68ae5cicj&redirect_uri=http%3A%2F%2Flocalhost%3A12345&response_type=code&state=dropbox
```

![image](https://user-images.githubusercontent.com/1094600/62344256-a272c900-b530-11e9-957d-0b803fe957c2.png)

**Comment by lemourin** [comment]
I am aware of that, you would need to supply your own keys (see Dropbox.cpp). It makes no sense to apply for review if the keys I use are public.

**Comment by sabrehagen** [comment]
Thanks for clarifying.
