### ISSUE TITLE
OneDrive link gets 'invalid state'

### ISSUE THREAD

**Issue by sabrehagen** [lemourin/libcloudstorage#12]
When linking OneDrive the OAuth flow succeeds, but the application returns `invalid state` after receiving the callback. Linking does not succeed.

![image](https://user-images.githubusercontent.com/1094600/62345865-42335580-b537-11e9-9643-b27b1c1d33b2.png)

**Comment by lemourin** [comment]
This is most likely caused by some other instance of libcloudstorage running in the background. All http servers libcloudstorage creates run on port 12345 by default. I guess that you are using `cloudstorage-fuse`, good idea would be to check there if the creation of http server succeeded.
