### ISSUE TITLE
desktop file is lacking a Categories= entry

### ISSUE THREAD

**Issue by probonopd** [lemourin/libcloudstorage#6]
The `*.desktop` file is lacking a `Categories=` entry.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

__electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).__. Please see the `category` key at https://www.electron.build/configuration/linux-other.

References:
* https://github.com/AppImage/appimage.github.io/issues/2
* https://github.com/AppImage/appimage.github.io/pull/688

**Comment by probonopd** [comment]
Thanks for fixing this in https://github.com/lemourin/libcloudstorage/commit/1343ae7ced08d3047a0d1f574ee8d64cf360b48c. If you could be so kind to ping me once a new release that contains the fix is out, then I could add the AppImage to the AppImageHub central directory of available AppImages. Thanks for your great work!

**Comment by lemourin** [comment]
The release already contains the fix, I retagged the version.

**Comment by probonopd** [comment]
Thank you
